@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.hcisland.world.storage;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;