@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.hcisland.client.gui.adapter;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;